### ISSUE TITLE
[Query]: How to have dependent validations

### ISSUE THREAD

**Issue by fr33m0nk** [mvallim/java-fluent-validator#66]
Hello, first of all I have to appreciate the efforts that have gone in this library and it's pretty amazing.

I had a question though, how to do validation on one field dependent on the other?

Following is my experiment :

```
public class Student {

    private final String enrolmentId;
    private final String id;

    public Student(Builder builder) {
        this.enrolmentId = builder.enrolmentId;
        this.id = builder.id;
    }

    public String getId() {
        return id;
    }

    public String getEnrolmentId() {
        return enrolmentId;
    }

    public static class Builder {

        private String enrolmentId;
        private String id;

        public static Builder newInstance()
        {
            return new Student.Builder();
        }

        public Builder setEnrolmentId(String enrolmentId) {
            this.enrolmentId = enrolmentId;
            return this;
        }

        public Builder setId(String id) {
            this.id = id;
            return this;
        }

        public Student build(){
            return new Student(this);
        }

    }

}
```

and its validator class

```
import br.com.fluentvalidator.AbstractValidator;
import com.api.request.models.Student;

import static br.com.fluentvalidator.predicate.LogicalPredicate.not;
import static br.com.fluentvalidator.predicate.StringPredicate.stringEmptyOrNull;

public class StudentValidator extends AbstractValidator<Student> {

    @Override
    public void  rules() {
        ruleFor(n -> n)
                .whenever(stringEmptyOrNull(n -> n.getEnrolmentId()))
                .must(not(stringEmptyOrNull(n -> n.getId())))
                .withMessage("Enrolment Id is null, Id must not be null");

        ruleFor(n -> n)
                .whenever(stringEmptyOrNull(n -> n.getId()))
                .must(not(stringEmptyOrNull(n -> n.getEnrolmentId())))
                .withMessage("Id is null, Enrolment Id must not be null");
    }
}
```

and then its test

```
import br.com.fluentvalidator.Validator;
import br.com.fluentvalidator.context.ValidationResult;
import com.api.request.models.Student;
import org.junit.Before;
import org.junit.Test;

import static com.google.common.truth.Truth.assertThat;

public class StudentValidatorTest {

    private Student.Builder studentBuilder;
    private Student student;
    private Validator<Student> studentValidator;

    @Before
    public void setUp() throws Exception {
        studentBuilder = Student.Builder.newInstance();
        studentValidator = new StudentValidator();
    }

    @Test
    public void shouldValidateStudentAndReturnFalse() {
        student = studentBuilder.build();
        final ValidationResult result = studentValidator.validate(student);
        assertThat(result.isValid()).isFalse();
    }
}
```

Sadly, the test results in a NullPointerException
```
java.lang.NullPointerException
	at br.com.fluentvalidator.rule.RuleProcessorStrategy.process(RuleProcessorStrategy.java:11)
	at br.com.fluentvalidator.rule.RuleBuilderPropertyImpl$ValidatorRuleInternal.apply(RuleBuilderPropertyImpl.java:184)
	at br.com.fluentvalidator.rule.RuleProcessorStrategy.process(RuleProcessorStrategy.java:11)
	at br.com.fluentvalidator.rule.RuleProcessorFailFast.lambda$process$0(RuleProcessorFailFast.java:9)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1249)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
	at br.com.fluentvalidator.rule.RuleProcessorFailFast.process(RuleProcessorFailFast.java:9)
	at br.com.fluentvalidator.rule.RuleBuilderPropertyImpl.apply(RuleBuilderPropertyImpl.java:42)
	at br.com.fluentvalidator.rule.Rule.apply(Rule.java:16)
	at br.com.fluentvalidator.rule.RuleProcessorStrategy.process(RuleProcessorStrategy.java:11)
	at br.com.fluentvalidator.rule.RuleProcessorStrategy.lambda$process$4(RuleProcessorStrategy.java:42)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at br.com.fluentvalidator.rule.RuleProcessorStrategy.process(RuleProcessorStrategy.java:43)
	at br.com.fluentvalidator.AbstractValidator.apply(AbstractValidator.java:120)
	at br.com.fluentvalidator.rule.RuleProcessorStrategy.process(RuleProcessorStrategy.java:15)
	at br.com.fluentvalidator.AbstractValidator.validate(AbstractValidator.java:84)
	at com.api.request.validators.StudentValidatorTest.validationTest(StudentValidatorTest.java:26)
```

Any help would greatly appreciated.

**Comment by mvallim** [comment]
Hi @fr33m0nk,

Thank you for feedback.

You are using ` whenever`, this expression should only be used when you want to pass an object to another `Validator`.

To run the test you want, I created a [playground](https://github.com/mvallim/java-fluent-validator/tree/master/src/test/java/br/com/fluentvalidator/playground) area in the tests that can help you better visualize how to use it.

I'm sorry this is not clear in the documentation.

Thank you very much,

**Comment by fr33m0nk** [comment]
@mvallim Thanks a ton for the playground!!! this definitely helped in gaining better understanding!!
